name: All New Release Helm Charts

on:
  workflow_dispatch: # Trigger manually or schedule
  push:
    branches:
      - main
    paths:
      - 'charts/**' 

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add dependency repositories
        run: |
          # Read repository URLs from a file
            while IFS= read -r REPO; do
                helm repo add $REPO
            done < ./helm-repos.txt

            helm repo update
      
      - name: Upgrade Helm Charts
        run: |
            CONFIG_FILE="./chart-versions.yaml"
            CHARTS_DIR="./charts"
            if [ ! -f "$CONFIG_FILE" ]; then
                echo "Configuration file $CONFIG_FILE not found! Exiting..."
                exit 1
            fi

            CHARTS=$(yq -r '.charts[] | .chart + " " + .version' "$CONFIG_FILE")

            while IFS= read -r CHART_VERSION; do
                CHART=$(echo "$CHART_VERSION" | awk '{print $1}')
                VERSION=$(echo "$CHART_VERSION" | awk '{print $2}')
                CHART_NAME=$(echo "$CHART_VERSION" | awk '{print $1}' |awk -F '/' '{print $2}')

                if helm show chart "$CHART" --version "$VERSION" >/dev/null 2>&1; then
                    if [ -d "$CHARTS_DIR/$CHART_NAME" ]; then
                      rm -rf $CHARTS_DIR/$CHART_NAME
                    fi
                    helm pull "$CHART" --version "$VERSION" --untar -d $CHARTS_DIR
                fi
            done <<< "$CHARTS"
          
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
