name: Repackage Charts

on:
  push:
    branches:
      - main

jobs:
  repackage-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull latest changes from main
        run: git pull origin main

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Create a new branch for repackaging
        run: |
          RANDOM_STRING=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)
          export NEW_BRANCH="repackage-charts-$(date +'%Y%m%d')-$RANDOM_STRING"
          echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV
          git checkout -b "$NEW_BRANCH"

      - name: Repackage Helm charts
        run: |
          mkdir -p packages
          for package in $(ls charts); do
            helm package charts/$package --destination packages
          done

      - name: Copy index.html to root
        run: |
          cp packages/index.html .
          git add packages
          git add index.html

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"
          git commit -m "Repackaged Helm charts and updated index.html"
          git push --set-upstream origin "$NEW_BRANCH"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.NEW_BRANCH }}
          title: "Repackage Helm Charts"
          body: "This pull request contains the repackaged Helm charts and updated index.html."
          base: gh-pages
