name: Repackage Charts

on:
  workflow_run:
    workflows:
      - Update Helm Charts # Name of the first workflow
    types:
      - completed
  workflow_dispatch: # Allows manual trigger


jobs:
  package-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull latest changes from main
        run: git pull origin main

      - name: Repackage Helm charts
        run: |
            #Package Helm charts
            CHARTS_DIR="./charts"
            PACKAGE_DIR="packages"
            REPO_URL="https://github.com/omegnet/helm_charts"
            mkdir -p packages
            for package in $(ls $CHARTS_DIR); do
                helm package charts/$package --destination $PACKAGE_DIR
            done

      - name: Checkout gh-pages branch
        run: |
            git fetch origin gh-pages
            git checkout gh-pages

      - name: Create a new branch indexing
        run: |
            RANDOM_STRING=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)
            export NEW_BRANCH="repackage-charts-$(date +'%Y%m%d')-$RANDOM_STRING"
            echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV
            git checkout -b "$NEW_BRANCH"
      
      - name: Indexing updated charts
        run: |
            helm repo index ./packages --url "$REPO_URL"

      - name: Copy index.html to root
        run: |
            ls -l ./packages
            ls -l
            # cp packages/index.yaml .
            # git add packages
            # git add index.yaml

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --local user.name "GitHub Actions Bot"
            git config --local user.email "actions@github.com"
            git add .
            if git diff --cached --quiet; then
                echo "No changes to commit or push."
                echo "SKIP_PR=true" >> $GITHUB_ENV
            else
                git commit -m "Repackaged Helm charts and updated index.yaml"
                git push --set-upstream origin "$NEW_BRANCH"
                echo "SKIP_PR=false" >> $GITHUB_ENV
            fi
            
      - name: create pull request
        if: ${{ env.SKIP_PR == 'false' }}
        run: |
            gh pr create \
            -B gh-pages \
            --title 'Merge "${{ env.NEW_BRANCH }}" into gh-pages' \
            --body 'This pull request updates the specified Helm charts to their desired versions as defined in `chart-versions.yaml`.'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    