name: Update Helm Charts

on:
  workflow_dispatch: # Trigger manually or schedule
  push:
    branches:
      - main

jobs:
  update-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull latest changes from main
        run: git pull origin main

      - name: Create a new branch
        run: |
            RANDOM_STRING=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)
            export NEW_BRANCH="update-helm-charts-$(date +'%Y%m%d')-$RANDOM_STRING"
            echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV
            git checkout -b "$NEW_BRANCH"

      - name: Install Helm
        run: |
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            chmod +x get_helm.sh
            ./get_helm.sh
        
      - name: Add Helm Repositories
        run: |
            # Read repository URLs from a file
            while IFS= read -r REPO; do
                helm repo add $REPO
            done < ./helm-repos.txt

            helm repo update

      - name: Upgrade Helm Charts
        run: |
            CONFIG_FILE="./chart-versions.yaml"
            CHARTS_DIR="./charts"
            if [ ! -f "$CONFIG_FILE" ]; then
                echo "Configuration file $CONFIG_FILE not found! Exiting..."
                exit 1
            fi

            CHARTS=$(yq -r '.charts[] | .chart + " " + .version' "$CONFIG_FILE")

            while IFS= read -r CHART_VERSION; do
                CHART=$(echo "$CHART_VERSION" | awk '{print $1}')
                VERSION=$(echo "$CHART_VERSION" | awk '{print $2}')
                CHART_NAME=$(echo "$CHART_VERSION" | awk '{print $1}' |awk -F '/' '{print $2}')

                if helm show chart "$CHART" --version "$VERSION" >/dev/null 2>&1; then
                    if [ -d "$CHARTS_DIR/$CHART_NAME" ]; then
                      rm -rf $CHARTS_DIR/$CHART_NAME
                    fi
                    helm pull "$CHART" --version "$VERSION" --untar -d $CHARTS_DIR
                fi
            done <<< "$CHARTS"

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --local user.name "GitHub Actions Bot"
            git config --local user.email "actions@github.com"
            git add .
            if git diff --cached --quiet; then
                echo "No changes to commit or push."
                echo "SKIP_PR=true" >> $GITHUB_ENV
            else
                git commit -m "Update Helm charts"
                git push --set-upstream origin "$NEW_BRANCH"
                echo "SKIP_PR=false" >> $GITHUB_ENV
            fi

      - name: Create Pull Request
        if: env.SKIP_PR == 'false'
        run: |
            gh pr create \
                -B main \
                --title "Merge '${{ env.NEW_BRANCH }}' into main" \
                --body "This pull request updates the specified Helm charts to their desired versions as defined in \`chart-versions.yaml\`."
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
