name: Release Charts

on:
  push:
    branches:
      - workflow

jobs:
  update-helm-charts:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Helm
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      # Step 3: Update Helm dependencies
      - name: Update Helm dependencies
        run: |
          for dir in $(find . -type f -name "Chart.yaml" -exec dirname {} \;); do
            echo "Updating dependencies for $dir"
            helm dependency update $dir || echo "No dependencies to update for $dir"
          done

      # Step 4: Commit changes if any
      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated update of Helm chart dependencies"
          fi

      # Step 5: Push changes back to the repository
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push

  release:
    needs: update-helm-charts  # Ensure this job runs after the update job
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Step 3: Process each chart release
      - name: Process each chart release
        run: |
          set -e  # Exit on any error
          for CHART_PATH in $(find ./charts -type f -name "Chart.yaml" -exec dirname {} \;); do
            CHART_NAME=$(basename $CHART_PATH)
            echo "Processing $CHART_NAME..."
            
            # Extract the version from Chart.yaml
            CURRENT_VERSION=$(grep "^version:" "$CHART_PATH/Chart.yaml" | awk '{print $2}')
            TAG_NAME="${CHART_NAME}-${CURRENT_VERSION}"

            echo "Checking if release $TAG_NAME already exists..."
            RELEASE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME)

            if echo "$RELEASE" | grep -q '"id":'; then
              echo "Release $TAG_NAME already exists and is up to date. Skipping..."
              continue
            fi

            # Run chart-releaser for new release
            echo "Packaging and indexing $CHART_NAME..."
            helm package $CHART_PATH
            helm repo index . --url https://github.com/${{ github.repository }}/releases

            # Create GitHub Release
            echo "Creating release for $TAG_NAME..."
            curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/releases \
              -d '{
                "tag_name": "'"$TAG_NAME"'",
                "name": "'"$TAG_NAME"'",
                "body": "Automated release for '"$CHART_NAME"' version '"$CURRENT_VERSION"'",
                "draft": false,
                "prerelease": false
              }'
          done
